'use client';
import{useEffect,useRef,useState}from'react';
import{BrainCircuit,Camera,RotateCcw,Settings2,X}from'lucide-react';
import type{DetectedObject,ObjectDetection}from'@tensorflow-models/coco-ssd';

export default function Home(){
 const v=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),model=useRef<ObjectDetection|null>(null);
 const[ok,setOk]=useState(false),[face,setFace]=useState<'user'|'environment'>('environment'),[zoom,setZoom]=useState(1),[pic,setPic]=useState<string|null>(null),[settings,setSettings]=useState(false),[detect,setDetect]=useState(true),[loading,setLoading]=useState(true),[objects,setObjects]=useState<DetectedObject[]>([]);
 useEffect(()=>{(async()=>{stream.current?.getTracks().forEach(t=>t.stop());try{const x=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:face},width:{ideal:3840},height:{ideal:2160}}});stream.current=x;if(v.current)v.current.srcObject=x;setOk(true)}catch{setOk(false)}})();return()=>stream.current?.getTracks().forEach(t=>t.stop())},[face]);
 useEffect(()=>{let live=true;(async()=>{try{await import('@tensorflow/tfjs');const coco=await import('@tensorflow-models/coco-ssd');model.current=await coco.load({base:'lite_mobilenet_v2'});if(live)setLoading(false)}catch{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 useEffect(()=>{let live=true,t:number;async function scan(){if(!live)return;if(detect&&ok&&model.current&&v.current?.readyState===4){try{setObjects((await model.current.detect(v.current,10,.55)))}catch{}}else if(!detect)setObjects([]);t=window.setTimeout(scan,220)}void scan();return()=>{live=false;clearTimeout(t)}},[detect,ok]);
 function snap(){const video=v.current;if(!video?.videoWidth)return;const vw=video.videoWidth,vh=video.videoHeight,viewRatio=video.clientWidth/video.clientHeight;let sw=vw,sh=vh;if(zoom>=1){if(vw/vh>viewRatio){sh=vh/zoom;sw=sh*viewRatio}else{sw=vw/zoom;sh=sw/viewRatio}}const sx=(vw-sw)/2,sy=(vh-sh)/2,maxWidth=2400,outW=Math.min(maxWidth,Math.round(sw)),outH=Math.round(outW/viewRatio);const c=document.createElement('canvas');c.width=outW;c.height=outH;const x=c.getContext('2d');if(!x)return;if(face==='user'){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(video,sx,sy,sw,sh,0,0,c.width,c.height);setPic(c.toDataURL('image/jpeg',.96))}
 function box(o:DetectedObject){const el=v.current;if(!el)return{};const r=el.getBoundingClientRect(),scale=(zoom<1?Math.min(r.width/el.videoWidth,r.height/el.videoHeight):Math.max(r.width/el.videoWidth,r.height/el.videoHeight)*zoom),ox=(r.width-el.videoWidth*scale)/2,oy=(r.height-el.videoHeight*scale)/2;let left=o.bbox[0]*scale+ox;if(face==='user')left=r.width-left-o.bbox[2]*scale;return{left,top:o.bbox[1]*scale+oy,width:o.bbox[2]*scale,height:o.bbox[3]*scale}}
 return <main><section><div className="view"><video ref={v} autoPlay muted playsInline style={{objectFit:zoom<1?'contain':'cover',transform:`scale(${zoom<1?1:zoom}) ${face==='user'?'scaleX(-1)':''}`}}/><header><button className={detect?'ai active':'ai'} onClick={()=>setDetect(!detect)} aria-label="Toggle object detection"><BrainCircuit/></button><b>HEIF <em>MAX</em></b><button onClick={()=>setSettings(true)} aria-label="Settings"><Settings2/></button></header><div className="detect-status"><i className={detect?'live':''}/>{loading?'Loading detector':detect?`${objects.length} object${objects.length===1?'':'s'} detected`:'Detection off'}</div>{detect&&objects.map((o,i)=><div className="object-box" key={o.class+i} style={box(o)}><span>{o.class} {Math.round(o.score*100)}%</span></div>)}{!ok&&<div className="allow"><Camera/><h1>Camera access needed</h1><p>Allow camera access to use the viewfinder and object detector.</p></div>}</div><nav><div className="zooms">{[.5,1,2].map(z=><button className={zoom===z?'on':''} onClick={()=>setZoom(z)} key={z}>{z}×</button>)}</div><p>PORTRAIT　 <em>PHOTO</em></p><div className="capture"><button className="thumb">{pic&&<img src={pic} alt="Last capture"/>}</button><button className="shutter" onClick={snap} disabled={!ok} aria-label="Take photo"><i/></button><button onClick={()=>setFace(face==='user'?'environment':'user')} aria-label="Switch camera"><RotateCcw/></button></div></nav>{pic&&<div className="review"><img src={pic} alt="Captured"/><button onClick={()=>setPic(null)}><X/></button><a href={pic} download="luma-photo.jpg">Save photo</a></div>}{settings&&<aside><button onClick={()=>setSettings(false)}><X/></button><h2>Capture settings</h2><p>Object detection: {detect?'On':'Off'}</p><small>Detection runs privately on this device. Quality depends on your camera and browser.</small></aside>}</section></main>}

